### ISSUE TITLE
Check that variables and regexes work correctly

### ISSUE THREAD

**Issue by amoeba** [amoeba/TownCrier#41]
@Schneebs noted that a chat trigger like `.*$NAME has discovered.*` doesn't work. See what's up.

**Comment by amoeba** [comment]
Hey @Schneebs, I just did some testing of this. I set up a regex of `.*$NAME has discovered.*` and did `/tell {mychar}, {mychar} has discovered a Tinkerer's Crystal` and my webhook was triggered. 


<img width="410" alt="Screen Shot 2019-04-23 at 9 27 41 PM" src="https://user-images.githubusercontent.com/563/56634491-a5474f00-660e-11e9-9813-aa274b413920.png">

<img width="583" alt="Screen Shot 2019-04-23 at 9 28 00 PM" src="https://user-images.githubusercontent.com/563/56634500-b2643e00-660e-11e9-9a05-2a347bd92a9a.png">

<img width="377" alt="Screen Shot 2019-04-23 at 9 28 16 PM" src="https://user-images.githubusercontent.com/563/56634509-b98b4c00-660e-11e9-8ec4-2d1c3a09b5ce.png">

is that what you tried out and didn't have luck with?

**Comment by Schneebs** [comment]
worked now, guess I had something else configured incorrectly.

**Comment by amoeba** [comment]
Right on, thanks for checking @Schneebs !
