### ISSUE TITLE
level event doesn't capture level to 275

### ISSUE THREAD

**Issue by Schneebs** [amoeba/TownCrier#43]
confirmed with tweek that he didn't see it either

**Comment by amoeba** [comment]
Huh, weird. What's the message in chat when you hit 275? TownCrier just matches this chat text pattern to trigger the webhooks for the `LEVEL` event:

https://github.com/amoeba/TownCrier/blob/47b2bb4f8b2048744e0d26af9343c6622e308ed1/PluginCore.cs#L77

**Comment by amoeba** [comment]
ah:

> You have reached the maximum level of 275!

I think most people would expect 275 to trigger the LEVEL event in this case. Thanks for reporting.

**Comment by amoeba** [comment]
Finally added this. Didn't test but I'm pretty sure it'll work. https://github.com/amoeba/TownCrier/releases/tag/v0.2.3. Thanks for the report!
