### ISSUE TITLE
Discord alerts broken again (11/9)

### ISSUE THREAD

**Issue by Schneebs** [amoeba/TownCrier#92]

**Comment by Schneebs** [comment]
@trevis i think you fixed it last time this happened

**Comment by amoeba** [comment]
Thanks for the report @Schneebs. What output are you seeing? The fix you're referencing was https://github.com/amoeba/TownCrier/commit/fafd91b1bcbbcd8a31ff10a1d40dfd19775aa0c4#diff-bae1041ad1fb2db156e2027646883a560f2ce088b2b5635f2ffe42a475bcf850R79 so is this something similar?

**Comment by Schneebs** [comment]
false alarm - I think discord had an issue the other day which caused the failures. Closing out

**Comment by amoeba** [comment]
Sounds good, thanks @Schneebs.
